### PR TITLE
Fix for ctz and clz

### LINKED ISSUE #21: ctz and clz for 0 gives unexpected result on older cpus
Tests fail on older cpus(intel sandy bridge and older). `ctz` and `clz` give 0 instead of bit width. 
Cpus tested: `e5-2670 v1`(fail), `i7-3820`(fail), `i7-4790K`(pass)

I would assume this has to do with the way that `tzcnt` and `lzcnt` are implemented on these cpus.

### PR DESCRIPTION
**Pull request by afinch7**
Closes #21

Ideally we should detect if a machine supports `tzcnt` and `lzcnt` correctly and use those instead when possible.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -10,3 +10,4 @@ rusty-tags.*
 docs/_build
 *~
 \#*\#
+.vscode
```
Comment (eira-fransham) [inline .gitignore]: This should be in your user `.gitignore` and not in the lightbeam `.gitignore`

File: src/backend.rs [hunk 2]
```diff
@@ -3230,10 +3230,161 @@ impl<'this, M: ModuleContext> Context<'this, M> {
...
-    unop!(i64_clz, lzcnt, Rq, u64, |a: u64| a.leading_zeros() as u64);
-    unop!(i32_ctz, tzcnt, Rd, u32, u32::trailing_zeros);
-    unop!(i64_ctz, tzcnt, Rq, u64, |a: u64| a.trailing_zeros() as u64);
+    pub fn i32_clz(&mut self) {
+        let val = self.pop();
+
+        let out_val = match val {
+            ValueLocation::Immediate(imm) =>
+                ValueLocation::Immediate(
+                    ((imm.as_int().unwrap() as i32).leading_zeros() as i32).into()
```
Comment (eira-fransham) [inline src/backend.rs]: You can use `imm.as_i32` here, which will correctly fail if given the wrong type. Lightbeam expects a validated Wasm file but this acts as a safeguard.

File: src/backend.rs [hunk 3]
```diff
@@ -3230,10 +3230,161 @@ impl<'this, M: ModuleContext> Context<'this, M> {
...
+        self.push(out_val);
+    }
+
+    pub fn i64_clz(&mut self) {
+        let val = self.pop();
+
+        let out_val = match val {
+            ValueLocation::Immediate(imm) =>
+                ValueLocation::Immediate(
+                    ((imm.as_int().unwrap() as u64).leading_zeros() as u64).into()
```
Comment (eira-fransham) [inline src/backend.rs]: As above, you can use `as_i64`

File: src/backend.rs [hunk 4]
```diff
@@ -3230,10 +3230,161 @@ impl<'this, M: ModuleContext> Context<'this, M> {
...
+                ),
+            ValueLocation::Stack(offset) => {
+                let offset = self.adjusted_offset(offset);
+                let temp = self.take_reg(I64).unwrap();
+                let temp_2 = self.take_reg(I64).unwrap();
```
Comment (eira-fransham) [inline src/backend.rs]: You need to free the unused temp register (`temp_2`) otherwise we'll leak registers. `self.free_value(ValueLocation::Reg(temp_2))` is the canonical way to do that, although it's kinda ugly. I'm trying to avoid reaching directly into `block_state` but you'll also see `self.block_state.regs.release(...)` too.

**Review by eira-fransham — CHANGES_REQUESTED** [review]
I'm impressed by how successfully you implemented a not-insignificant change on this project on your first try, the abstractions are pretty eclectic and easy to get wrong (I might switch to using some kind of `Rc`-like type that automatically refcounts to avoid the register-leaking problems that you have here). There's only one error that needs to be fixed, my other comments are just things that could be better but that aren't absolutely necessary.

File: .gitignore (hunk 1 above)
Comment (afinch7) [reply .gitignore]: Didn't even know you could have a user `.gitignore`. 👍

**Comment by afinch7** [comment]
@Vurich Never worked on compilers much before, but I would say automatic resource allocation is the way to go here. I might give that one a try after I get this merged.

**Comment by eira-fransham** [comment]
> @Vurich Never worked on compilers much before, but I would say automatic resource allocation is the way to go here. I might give that one a try after I get this merged.

Automatic resource allocation is good for sure, but it's much more complicated than it may seem at first glance because some instructions require allocating specific registers and others require it to be possible to allocate a register even if all have been allocated already (by pushing and popping). Manually allocating and freeing is a PITA but makes it a lot easier to deal with edge-cases since you only need to maintain invariants at function boundaries. Ideally we'd have a better framework to handle this, but it's a lot of work.

File: src/backend.rs [hunk 5]
```diff
@@ -3241,30 +3241,46 @@ impl<'this, M: ModuleContext> Context<'this, M> {
...
-                dynasm!(self.asm
-                    ; bsr Rd(temp.rq().unwrap()), [rsp + offset]
-                    ; mov Rd(temp_2.rq().unwrap()), DWORD 0x3fu64 as _
-                    ; cmove Rd(temp.rq().unwrap()), Rd(temp_2.rq().unwrap())
-                    ; mov Rd(temp_2.rq().unwrap()), DWORD 0x1fu64 as _
-                    ; xor Rd(temp.rq().unwrap()), Rd(temp_2.rq().unwrap())
-                );
-                self.free_value(ValueLocation::Reg(temp_2));
-                ValueLocation::Reg(temp)
+                if is_x86_feature_detected!("lzcnt") {
```
Comment (eira-fransham) [inline src/backend.rs:3244]: Thanks! This is fine for now but we want to use Cranelift's target system eventually (it's currently not usable outside Cranelift though)

**Review by eira-fransham — APPROVED** [review]
Can you run rustfmt quickly? There are some empty lines and that should remove them and fix any other formatting issues at the same time. Otherwise this looks perfect. Thank you!
